apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

# Patch my-deployment such that it uses 3 replicas instead of 2.
# The apiVersion, kind, name, and namespace together uniquely identify the resources being updated.
# In this case, the namespace is "default" — so it's not specified.
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-deployment
  spec:
    replicas: 3
