apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

# Patch my-deployment such that it uses 3 replicas instead of 2.
patchesJson6902:
- target: # Uniquely identify the resource you want to update.
    version: v1
    kind: Deployment
    name: my-deployment # Reminder: There can only be one Deployment named my-deployment in a namespace.
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
