apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

# Patch my-deployment such that it uses 3 replicas instead of 2.
patchesJson6902:
- target:
    kind: Deployment
    name: my-deployment # We're using the unique identifier.
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
