apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

# Deploy version 2.0 of the Docker container image, instead of version 1.0.
images:
- name: us-docker.pkg.dev/google-samples/containers/gke/hello-app
  newTag: '2.0'
