apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  # We're using Google Cloud's external load balancer.
  # This will generate a public IP address.
  type: LoadBalancer
  # Select the Pods that make up this Service.
  selector:
    pod-label: my-pod
  ports:
  - port: 80
    targetPort: 8080
